max_steps: 100
use_terminal: false
terminal_visibility: false
tool_preset: full
tool_supplements:
- ast_grep
- todo
approval:
  enabled: true
  tools:
    write:
      allowed_paths:
      - ./*
    edit:
      allowed_paths:
      - ./*
