"""Pydantic value objects for the KB store.

Shared by KbPersistence and KbRetriever. All models are frozen with
extra="forbid" per rules/type-safety.md rules 10-16.

Three-state isolation semantics (KbFilter):
    None  = do not filter this dimension (global)
    ""    = only public / no-scope entries
    "val" = only entries isolated to that value

Isolation fields on KbEntry / KbUpsertRequest default to "" (public),
not None — avoids SQLite UNIQUE NULL ambiguity (DESIGN.md §2.2).
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class KbAction(StrEnum):
    """KB action enum — shared by KbTool, CLI, and REST route."""
    SEARCH = "search"
    GET = "get"
    SET = "set"
    DELETE = "delete"
    LIST = "list"


class KbFilter(BaseModel):
    """Multi-dimensional filter with three-state semantics per dimension.

    None = global (do not filter); "" = public-only; "val" = isolated.
    New dimensions can be added without breaking backends (forward-compatible).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    task_id: str | None = None
    session_id: str | None = None
    category: str | None = None


class KbEntry(BaseModel):
    """KB entry — the read result model.

    entry_id is generated by persistence (Snowflake); callers do not set it.
    All isolation dimensions have concrete values ("" = public/no-scope).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    entry_id: int
    key: str
    value: str
    task_id: str = ""
    session_id: str = ""
    category: str = ""
    tags: str = ""
    created_at: int
    updated_at: int


class KbUpsertRequest(BaseModel):
    """Write request. entry_id is generated by persistence; callers omit it."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    key: str
    value: str
    task_id: str = ""
    session_id: str = ""
    category: str = ""
    tags: str = ""


class KbSearchResult(BaseModel):
    """Search result with relevance score.

    score semantics are defined by the retriever backend
    (BM25 rank / cosine / weighted blend).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    entry: KbEntry
    score: float = 0.0


class KbControlRequest(BaseModel):
    """Shared request envelope for KB operations.

    Used by both the CLI (constructs + model_dump for HTTP) and the REST route
    (model_validate from HTTP body). Single schema, two serialization directions.
    Response formatting is handled by formatting.py (not this model).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    action: KbAction
    query_or_key: str | None = None
    value: str | None = None
    filter: KbFilter = KbFilter()
    limit: int = Field(default=20, ge=1, le=100)
