"""macOS LOCAL runtime: Seatbelt profile compilation and startup validation.

Compiles file-policy rules into an SBPL profile and launches through
``sandbox-exec -f <profile>``. File reads are broadly allowed; READ_ONLY is
not a workspace-only read boundary. Network deny rules are emitted unless
``settings.network`` is true.

``resolve_available`` canonicalizes workspace/extra roots before compilation
and executes a constant no-op to validate the compiled launcher. Engine
selection is owned by ``selection.py``. Confirmed pre-command unavailability
may degrade to HOST; permission/configuration errors propagate.

The profile file outlives resolution and all bound shell consumers.
``close()`` removes the runtime's profiles after those consumers close.
Real macOS shell execution and file/network boundaries are exercised by
``test_seatbelt_live.py``; the FULL report alone is not proof of every rule
or arbitrary program's safety.
"""

from __future__ import annotations

import contextlib
import tempfile
from pathlib import Path
from typing import assert_never

from modex_agent.workspace.boundary import canonicalize_path

from .platform import Platform, get_platform, resolve_shell
from .runtime import (
    HostRuntime,
    ResolvedSandbox,
    SandboxRuntime,
    validate_local_startup,
)
from .settings import SandboxBackend, SandboxSettings, WriteSurface
from .types import EnforcementLevel

_get_platform = get_platform
_resolve_host_shell = resolve_shell

__all__ = ["SeatbeltRuntime", "compile_seatbelt_profile"]


def _profile_path(path: Path) -> str:
    """Quote a filesystem path as SBPL data, never as profile syntax."""
    escaped = path.as_posix().replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped.replace("\n", "\\n").replace("\r", "\\r") + '"'


def compile_seatbelt_profile(
    settings: SandboxSettings, workspace_root: Path
) -> str:
    """Compile an SBPL v1 profile without launching or probing the engine.

    Protected-path canonicalization may access the filesystem.

    Boundary semantics (mirrors the PRD's two-family model):

    - ``READ_ONLY``: the whole volume is readable, nothing is writable.
    - ``WORKSPACE_WRITE``: the whole volume is readable; writes are allowed
      only under the workspace root and the declared ``writable_roots``;
      ``protected_subpaths`` (default ``[".git"]``) are denied again *after*
      those allows so the trailing deny shadows them.
    - ``full``: no file boundary rules at all (the guard layer
      still applies independently of backend selection).

    ``network`` is orthogonal to the file policy and denied by default.
    """
    match settings.exclusive.write_surface:
        case WriteSurface.NONE:
            lines = [
                "(version 1)",
                "",
                ";; generated by modex_agent.sandbox.seatbelt_runtime - do not edit",
                "",
                ";; write surface none: everything readable, nothing writable",
                "(allow file-read*)",
                "(deny file-write*)",
            ]
        case WriteSurface.WORKSPACE | WriteSurface.ROOTS:
            writable_roots = (
                [workspace_root, *settings.exclusive.writable_roots]
                if settings.exclusive.write_surface is WriteSurface.WORKSPACE
                else list(settings.exclusive.writable_roots)
            )
            lines = [
                "(version 1)",
                "",
                ";; generated by modex_agent.sandbox.seatbelt_runtime - do not edit",
                "",
                ";; bounded writes: everything readable, writes denied by default",
                "(allow file-read*)",
                "(deny file-write*)",
            ]
            # Trailing rules win: allow writes under each root first...
            for root in writable_roots:
                lines.append(f"(allow file-write* (subpath {_profile_path(root)}))")
            # ...then shadow the protected subpaths back to deny.
            for root in writable_roots:
                for sub in settings.exclusive.protected_subpaths:
                    protected = canonicalize_path(sub, base=root)
                    lines.append(f"(deny file-write* (subpath {_profile_path(protected)}))")
        case WriteSurface.FULL:
            lines = [
                "(version 1)",
                "",
                ";; generated by modex_agent.sandbox.seatbelt_runtime - do not edit",
                "",
                ";; danger-full-access: no file boundary (guard layer still applies)",
                "(allow file-read*)",
                "(allow file-write*)",
            ]
        case unreachable:
            assert_never(unreachable)

    # The implicit deny policy also denies launching the shell and its children.
    # Permit execution explicitly without relaxing the file-write envelope.
    lines.extend(["(allow process-exec)", "(allow process-fork)"])
    lines.append("(allow network*)" if settings.network else "(deny network*)")

    return "\n".join(lines) + "\n"


def _write_profile_tempfile(profile_text: str) -> Path:
    """Materialize the profile in the system temp dir (outlives resolve())."""
    fd, raw_path = tempfile.mkstemp(prefix="modex-seatbelt-", suffix=".sb")
    try:
        with open(fd, "w", encoding="utf-8") as handle:
            handle.write(profile_text)
    except OSError:
        with contextlib.suppress(OSError):
            Path(raw_path).unlink(missing_ok=True)
        raise
    return Path(raw_path)


class SeatbeltRuntime(SandboxRuntime):
    """macOS local family: policy → SBPL profile → ``sandbox-exec -f`` argv.

    The selector chooses the engine. ``resolve`` writes the profile;
    ``resolve_available`` also executes a startup no-op. Direct construction
    retains a platform gate, and ``close`` owns profile cleanup.
    """

    def __init__(self) -> None:
        self._profiles: list[Path] = []

    async def close(self) -> None:
        for path in self._profiles:
            path.unlink(missing_ok=True)
        self._profiles.clear()

    async def _validate_startup(self, resolved: ResolvedSandbox, workspace_root: Path) -> None:
        await validate_local_startup(resolved, workspace_root)

    async def resolve(
        self, settings: SandboxSettings, workspace_root: Path
    ) -> ResolvedSandbox:
        if _get_platform() is not Platform.MACOS:
            host = await HostRuntime().resolve(settings, workspace_root)
            return host.model_copy(
                update={"degraded_reason": "seatbelt runtime requires macOS"}
            )

        profile_text = compile_seatbelt_profile(settings, workspace_root)
        profile_path = _write_profile_tempfile(profile_text)
        self._profiles.append(profile_path)
        prefix = ["sandbox-exec", "-f", str(profile_path)]

        shell = _resolve_host_shell()
        shell_argv = [*prefix, shell, "--noprofile", "--norc", "-i"] if shell else []

        return ResolvedSandbox(
            backend=SandboxBackend.LOCAL,
            enforcement=EnforcementLevel.FULL,
            shell_argv=shell_argv,
            one_shot_command_argv_prefix=prefix,
        )
