"""Tests for SeatbeltRuntime — profile compilation and argv resolution.

Ticket 06 (docs/design/sandbox-integration/tickets.md):

- profile text snapshot matrix: READ_ONLY / WORKSPACE_WRITE /
  DANGER_FULL_ACCESS × network on/off × writable_roots / protected_subpaths
- the generated profile is a *real* boundary: global ``deny file-write*`` is
  always present (never the legacy ``(allow default)`` fake isolation);
  protected-subpath denies come after the allows (SBPL: last rule wins)
- argv shape: ``sandbox-exec -f <profile>`` + host bash tail; the profile
  temp file exists on disk and its bytes equal the compiled profile
- degradation: probe failure → HOST with a degraded_reason (honest
  reporting); non-macOS construction → HOST as well
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import pytest

import modex_agent.sandbox.seatbelt_runtime as seatbelt_mod
from modex_agent.sandbox.engine_probe import ProbeResult
from modex_agent.sandbox.platform import Platform
from modex_agent.sandbox.seatbelt_runtime import (
    SeatbeltRuntime,
    compile_seatbelt_profile,
)
from modex_agent.sandbox.settings import (
    SandboxBackend,
    SandboxPolicy,
    SandboxSettings,
)
from modex_agent.sandbox.types import EnforcementLevel

WS = Path("/Users/dev/project").resolve()

# ---------------------------------------------------------------------------
# Fixtures — patch the platform + shell seams (the runtime never probes;
# probe-failure degradation is covered via the selector in TestDegradation).
# ---------------------------------------------------------------------------


@pytest.fixture
def patch_platform(monkeypatch: pytest.MonkeyPatch) -> Callable[[str], None]:
    """Patch get_platform() in the namespace the runtime gate reads."""

    def _patch(platform_name: str) -> None:
        monkeypatch.setattr(
            seatbelt_mod, "_get_platform", lambda: Platform(platform_name)
        )

    return _patch


@pytest.fixture
def patch_shell(monkeypatch: pytest.MonkeyPatch) -> Callable[[str | None], None]:
    """Patch the host-shell seam inside seatbelt_runtime."""

    def _patch(shell: str | None) -> None:
        monkeypatch.setattr(seatbelt_mod, "_resolve_host_shell", lambda: shell)

    return _patch


# ---------------------------------------------------------------------------
# Profile snapshots (pure function — no seams needed)
# ---------------------------------------------------------------------------


class TestProfileReadOnly:
    def test_snapshot_with_network_denied(self) -> None:
        settings = SandboxSettings(policy=SandboxPolicy.READ_ONLY, network=False)
        assert compile_seatbelt_profile(settings, WS) == (
            "(version 1)\n"
            "\n"
            ";; generated by modex_agent.sandbox.seatbelt_runtime - do not edit\n"
            "\n"
            ";; read-only: everything readable, nothing writable\n"
            "(allow file-read*)\n"
            "(deny file-write*)\n"
            "(deny network*)\n"
        )

    def test_snapshot_with_network_allowed(self) -> None:
        settings = SandboxSettings(policy=SandboxPolicy.READ_ONLY, network=True)
        profile = compile_seatbelt_profile(settings, WS)
        assert "(deny network*)" not in profile
        assert "(deny file-write*)" in profile


class TestProfileWorkspaceWrite:
    def test_snapshot_default_protected_git(self) -> None:
        settings = SandboxSettings(policy=SandboxPolicy.WORKSPACE_WRITE, network=False)
        assert compile_seatbelt_profile(settings, WS) == (
            "(version 1)\n"
            "\n"
            ";; generated by modex_agent.sandbox.seatbelt_runtime - do not edit\n"
            "\n"
            ";; workspace-write: everything readable, writes denied by default\n"
            "(allow file-read*)\n"
            "(deny file-write*)\n"
            f'(allow file-write* (subpath "{WS.as_posix()}"))\n'
            f'(deny file-write* (subpath "{WS.as_posix()}/.git"))\n'
            "(deny network*)\n"
        )

    def test_snapshot_extra_writable_roots_and_protected_subpaths(self) -> None:
        build_root = Path("/tmp/build").resolve()
        log_root = Path("/var/log/app").resolve()
        settings = SandboxSettings(
            policy=SandboxPolicy.WORKSPACE_WRITE,
            network=True,
            writable_roots=[build_root, log_root],
            protected_subpaths=[".git", "secrets"],
        )
        profile = compile_seatbelt_profile(settings, WS)
        # Allow rules for every writable root (workspace first, then declared).
        assert (
            f'(allow file-write* (subpath "{WS.as_posix()}"))\n'
            f'(allow file-write* (subpath "{build_root.as_posix()}"))\n'
            f'(allow file-write* (subpath "{log_root.as_posix()}"))\n'
        ) in profile
        # Deny rules for every protected subpath of every root, AFTER the
        # allows (SBPL: the last matching rule wins — the trailing deny
        # shadows the broader allow).
        deny_block = (
            f'(deny file-write* (subpath "{WS.as_posix()}/.git"))\n'
            f'(deny file-write* (subpath "{WS.as_posix()}/secrets"))\n'
            f'(deny file-write* (subpath "{build_root.as_posix()}/.git"))\n'
            f'(deny file-write* (subpath "{build_root.as_posix()}/secrets"))\n'
            f'(deny file-write* (subpath "{log_root.as_posix()}/.git"))\n'
            f'(deny file-write* (subpath "{log_root.as_posix()}/secrets"))\n'
        )
        assert deny_block in profile
        assert profile.index(deny_block) > profile.index(
            f'(allow file-write* (subpath "{log_root.as_posix()}"))'
        )
        # network=True → no network deny.
        assert "(deny network*)" not in profile

    def test_empty_protected_subpaths_only_allows(self) -> None:
        settings = SandboxSettings(
            policy=SandboxPolicy.WORKSPACE_WRITE,
            network=False,
            protected_subpaths=[],
        )
        profile = compile_seatbelt_profile(settings, WS)
        assert profile.count("(deny file-write*") == 1  # only the global deny


class TestProfileDangerFullAccess:
    def test_snapshot_no_file_boundary(self) -> None:
        settings = SandboxSettings(
            policy=SandboxPolicy.DANGER_FULL_ACCESS, network=False
        )
        assert compile_seatbelt_profile(settings, WS) == (
            "(version 1)\n"
            "\n"
            ";; generated by modex_agent.sandbox.seatbelt_runtime - do not edit\n"
            "\n"
            ";; danger-full-access: no file boundary (guard layer still applies)\n"
            "(allow file-read*)\n"
            "(allow file-write*)\n"
            "(deny network*)\n"
        )


class TestProfileBoundaryTruth:
    """The profile must be a real boundary — the anti-regression class."""

    @pytest.mark.parametrize(
        ("policy", "network"),
        [
            (SandboxPolicy.READ_ONLY, False),
            (SandboxPolicy.READ_ONLY, True),
            (SandboxPolicy.WORKSPACE_WRITE, False),
            (SandboxPolicy.WORKSPACE_WRITE, True),
        ],
    )
    def test_bounded_policies_never_allow_default(
        self, policy: SandboxPolicy, network: bool
    ) -> None:
        """The legacy isolation.py bug was (allow default) — fake isolation."""
        settings = SandboxSettings(policy=policy, network=network)
        profile = compile_seatbelt_profile(settings, WS)
        assert "(allow default)" not in profile
        assert "(deny file-write*)" in profile
        assert profile.startswith("(version 1)")


# ---------------------------------------------------------------------------
# ResolvedSandbox argv shape (macOS, probe available)
# ---------------------------------------------------------------------------


class TestResolveArgv:
    async def test_shell_argv_shape_and_profile_file_exists(
        self,
        monkeypatch: pytest.MonkeyPatch,
        patch_platform: Callable[[str], None],
        patch_shell: Callable[[str | None], None],
    ) -> None:
        patch_platform("darwin")
        patch_shell("/bin/bash")

        settings = SandboxSettings(policy=SandboxPolicy.WORKSPACE_WRITE)
        resolved = await SeatbeltRuntime().resolve(settings, WS)

        assert resolved.backend is SandboxBackend.LOCAL
        assert resolved.enforcement is EnforcementLevel.FULL
        assert resolved.degraded_reason is None

        # shell_argv = sandbox-exec -f <profile> + host bash tail.
        assert resolved.shell_argv[0] == "sandbox-exec"
        assert resolved.shell_argv[1] == "-f"
        profile_path = Path(resolved.shell_argv[2])
        assert profile_path.exists()
        assert profile_path.suffix == ".sb"
        assert resolved.shell_argv[3:] == ["/bin/bash", "--noprofile", "--norc", "-i"]

        # The temp file carries exactly the compiled profile.
        expected_profile = compile_seatbelt_profile(settings, WS)
        assert profile_path.read_text(encoding="utf-8") == expected_profile

        # One-shot prefix is the same wrapper without the shell tail.
        assert resolved.one_shot_command_argv_prefix == [
            "sandbox-exec",
            "-f",
            str(profile_path),
        ]

    async def test_no_bash_found_empty_shell_argv(
        self,
        monkeypatch: pytest.MonkeyPatch,
        patch_platform: Callable[[str], None],
        patch_shell: Callable[[str | None], None],
    ) -> None:
        patch_platform("darwin")
        patch_shell(None)

        resolved = await SeatbeltRuntime().resolve(
            SandboxSettings(policy=SandboxPolicy.WORKSPACE_WRITE), WS
        )
        assert resolved.shell_argv == []
        # One-shot prefix still carries the wrapper.
        assert resolved.one_shot_command_argv_prefix[0] == "sandbox-exec"


# ---------------------------------------------------------------------------
# Degradation paths
# ---------------------------------------------------------------------------


class TestDegradation:
    async def test_selector_probe_failure_degrades_to_host_honestly(
        self,
        monkeypatch: pytest.MonkeyPatch,
        patch_platform: Callable[[str], None],
        patch_shell: Callable[[str | None], None],
    ) -> None:
        """The selector (selection.resolve_selection) probes seatbelt; a
        failed probe yields HostRuntime(reason) — the reason lands in
        ResolvedSandbox verbatim (honest reporting)."""
        import modex_agent.sandbox.selection as selection_mod
        from modex_agent.sandbox.selection import resolve_selection, select_runtime

        monkeypatch.setattr(
            selection_mod, "_get_platform", lambda: Platform.MACOS
        )
        patch_shell("/bin/bash")

        async def failing_probe() -> ProbeResult:
            return ProbeResult(available=False, detail="not found on PATH")

        monkeypatch.setattr(selection_mod, "probe_seatbelt", failing_probe)

        selection = await resolve_selection(SandboxBackend.AUTO)
        resolved = await select_runtime(selection).resolve(
            SandboxSettings(policy=SandboxPolicy.WORKSPACE_WRITE), WS
        )
        assert resolved.backend is SandboxBackend.HOST
        assert resolved.enforcement is EnforcementLevel.NONE
        assert resolved.degraded_reason is not None
        assert "sandbox-exec" in resolved.degraded_reason

    async def test_non_macos_is_host(
        self,
        monkeypatch: pytest.MonkeyPatch,
        patch_platform: Callable[[str], None],
        patch_shell: Callable[[str | None], None],
    ) -> None:
        patch_platform("linux")
        patch_shell("/bin/bash")

        resolved = await SeatbeltRuntime().resolve(
            SandboxSettings(policy=SandboxPolicy.WORKSPACE_WRITE), WS
        )
        assert resolved.backend is SandboxBackend.HOST
        assert resolved.degraded_reason is not None
        assert "macOS" in resolved.degraded_reason
