"""Scope declaration package — declaration types, loading, position-derived
defaults, two-phase tree validation, profiles, and the pure-function
ScopeCompiler (ADR-0042, SPEC §3 + §7). Pure types, parsing, validation,
and compilation: zero consumer wiring until ticket 07 boots the first pool
from a declaration. W3a moved the assembly-schema types here: component
slots/factories (``components``), the capability protocol
(``capability``), ``AssemblySpec`` (``assembly_spec``), and
``ComponentRegistry`` (``component_registry``) — the plugins package
keeps the runtime machinery and imports them downward.
"""

from modex_agent.scope.assembly_spec import (
    AssemblySpec,
    MemoryOverrides,
    ToolEntry,
)
from modex_agent.scope.capability import (
    AgentDeclarationView,
    AgentDeclaredFields,
    Capability,
    CapabilityBinding,
    CapabilityConfig,
    CapabilityContribution,
    CapabilityError,
    CapabilitySupply,
    CapabilityWiring,
    ChildSummary,
    CompiledCapability,
    DerivedToolOrigin,
    DerivedToolSpec,
    FinalRosterView,
    PoolSupplyAgentEntry,
    PoolSupplyView,
    PromptSectionSpec,
    SectionPlacement,
    TreePositionView,
)
from modex_agent.scope.compiler import (
    AgentProvenance,
    CapabilityContributionKind,
    CapabilityContributionProvenance,
    CapabilityGateResult,
    CapabilityProvenance,
    CapabilityState,
    CompiledAgent,
    FieldProvenance,
    HookEntryProvenance,
    HookOrigin,
    ProvenanceLayer,
    ScopeCompilation,
    ToolEntryProvenance,
    compile_scope,
)
from modex_agent.scope.component_registry import (
    ComponentNotFoundError,
    ComponentRegistry,
    PluginSource,
    TypedBundle,
)
from modex_agent.scope.components import (
    AgentType,
    ComponentFactory,
    ComponentSlot,
    HookFactory,
    HookRunnerKind,
    MemoryHookFactory,
    PrototypeFactory,
    ReactHookFactory,
    SimpleFactory,
)
from modex_agent.scope.defaults import (
    POSITION_DEFAULT_HOOKS,
    MemoryPreset,
    PositionDefaults,
    RegistrationTiming,
    defaults_for_position,
    effective_defaults,
    memory_config_for_position,
    position_default_hooks,
)
from modex_agent.scope.loader import (
    ScopeDeclarationError,
    load_dynamic_workspace_declarations,
    load_scope_declaration,
)
from modex_agent.scope.overlay import (
    AgentOverlay,
    PoolOverlay,
    ScopeOverlay,
    apply_scope_overlay,
)
from modex_agent.scope.profile import (
    STANDARD_PROFILES,
    Profile,
    ProfileStore,
    merge_memory_declarations,
)
from modex_agent.scope.seam import ScopeGenerationTracker, spec_hash
from modex_agent.scope.spec import (
    AgentSpec,
    MemoryDeclaration,
    ModelRef,
    PoolSpec,
    ScopeKind,
    ScopeSpec,
    SessionMemoryOverride,
    WorkspacePathsSpec,
    WorkspacePersistenceSpec,
    WorkspaceSpec,
)
from modex_agent.scope.validator import (
    EffectiveAgentConfig,
    GraphAgentReference,
    ProfileDeclaration,
    RuleId,
    ScopeValidationIssue,
    validate_declaration,
    validate_effective_configs,
)

__all__ = [
    "POSITION_DEFAULT_HOOKS",
    "AgentDeclaredFields",
    "AgentDeclarationView",
    "AgentProvenance",
    "AgentOverlay",
    "AgentSpec",
    "AgentType",
    "AssemblySpec",
    "Capability",
    "CapabilityBinding",
    "CapabilityConfig",
    "CapabilityContribution",
    "CapabilityContributionKind",
    "CapabilityContributionProvenance",
    "CapabilityError",
    "CapabilityGateResult",
    "CapabilityProvenance",
    "CapabilityState",
    "CapabilitySupply",
    "CapabilityWiring",
    "ChildSummary",
    "CompiledAgent",
    "CompiledCapability",
    "ComponentFactory",
    "ComponentNotFoundError",
    "ComponentRegistry",
    "ComponentSlot",
    "DerivedToolOrigin",
    "DerivedToolSpec",
    "EffectiveAgentConfig",
    "FieldProvenance",
    "FinalRosterView",
    "GraphAgentReference",
    "HookEntryProvenance",
    "HookFactory",
    "HookOrigin",
    "HookRunnerKind",
    "MemoryDeclaration",
    "MemoryHookFactory",
    "MemoryOverrides",
    "MemoryPreset",
    "ModelRef",
    "PluginSource",
    "PoolSpec",
    "PoolOverlay",
    "PoolSupplyAgentEntry",
    "PoolSupplyView",
    "PositionDefaults",
    "Profile",
    "ProfileDeclaration",
    "ProfileStore",
    "PromptSectionSpec",
    "ProvenanceLayer",
    "PrototypeFactory",
    "ReactHookFactory",
    "RegistrationTiming",
    "RuleId",
    "STANDARD_PROFILES",
    "ScopeCompilation",
    "ScopeDeclarationError",
    "ScopeGenerationTracker",
    "ScopeKind",
    "ScopeOverlay",
    "ScopeSpec",
    "ScopeValidationIssue",
    "SectionPlacement",
    "SessionMemoryOverride",
    "SimpleFactory",
    "ToolEntry",
    "ToolEntryProvenance",
    "TreePositionView",
    "TypedBundle",
    "WorkspacePathsSpec",
    "WorkspacePersistenceSpec",
    "WorkspaceSpec",
    "apply_scope_overlay",
    "compile_scope",
    "defaults_for_position",
    "effective_defaults",
    "load_dynamic_workspace_declarations",
    "load_scope_declaration",
    "memory_config_for_position",
    "merge_memory_declarations",
    "position_default_hooks",
    "spec_hash",
    "validate_declaration",
    "validate_effective_configs",
]
