#!/usr/bin/env python3
"""
示例3: 命令行执行
==============

这个示例展示如何执行 shell 命令而不是 Python 代码。

适用于：运行系统命令、调用外部工具、执行脚本文件
注意：SubprocessSandbox 支持命令执行，但 E2BSandbox 也支持
"""

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from framework.sandbox import get_default_sandbox, SandboxConfig


async def main():
    """演示命令行执行"""

    print("=" * 60)
    print("示例3: 命令行执行")
    print("=" * 60)

    sandbox = get_default_sandbox()

    # 示例3.1: 执行简单命令
    print("\n【场景3.1】执行 echo 命令")
    result1 = await sandbox.execute_command("echo 'Hello from sandbox!'")
    print(f"执行成功: {result1.success}")
    print(f"标准输出: {result1.stdout.strip()}")
    print(f"退出码: {result1.exit_code}")

    # 示例3.2: 执行多行命令
    print("\n【场景3.2】执行多行命令（使用分号分隔）")
    result2 = await sandbox.execute_command("pwd; echo '---'; ls -la")
    print(f"执行成功: {result2.success}")
    print(f"输出:\n{result2.stdout}")

    # 示例3.3: 执行带管道和重定向的命令
    print("\n【场景3.3】执行复杂命令（管道）")
    result3 = await sandbox.execute_command("echo -e 'apple\\nbanana\\napple\\ncherry\\napple' | sort | uniq -c")
    print(f"执行成功: {result3.success}")
    print(f"输出:\n{result3.stdout}")

    # 示例3.4: 执行失败命令
    print("\n【场景3.4】执行会失败的命令")
    result4 = await sandbox.execute_command("ls /nonexistent_directory")
    print(f"执行成功: {result4.success}")
    print(f"退出码: {result4.exit_code}")
    print(f"错误输出: {result4.stderr.strip()}")

    # 示例3.5: 在产物目录中创建文件
    print("\n【场景3.5】使用命令行创建产物文件")

    # 首先执行 Python 代码设置环境
    setup_code = """
import os
artifacts_dir = os.environ.get('SANDBOX_ARTIFACTS_DIR', '/tmp/artifacts')
os.makedirs(artifacts_dir, exist_ok=True)
print(f"产物目录: {artifacts_dir}")
"""
    setup_result = await sandbox.execute(setup_code)
    print(f"设置产物目录: {setup_result.stdout.strip()}")

    # 然后使用命令行创建文件
    result5 = await sandbox.execute_command(
        "echo 'Generated by shell command' > \$SANDBOX_ARTIFACTS_DIR/shell_output.txt"
    )
    print(f"命令执行成功: {result5.success}")

    # 查看产物
    artifacts_result = await sandbox.execute_command("ls -la \$SANDBOX_ARTIFACTS_DIR/")
    print(f"产物目录内容:\n{artifacts_result.stdout}")

    # 示例3.6: 执行 Python 脚本文件
    print("\n【场景3.6】执行 Python 脚本文件")

    # 先创建脚本
    script_code = """
import os
artifacts_dir = os.environ.get('SANDBOX_ARTIFACTS_DIR', '/tmp/artifacts')
os.makedirs(artifacts_dir, exist_ok=True)

script_content = '''
#!/usr/bin/env python3
import sys

print(f"Python version: {sys.version}")
print(f"Arguments: {sys.argv}")

# 计算阶乘
def factorial(n):
    if n <= 1:
        return 1
    return n * factorial(n - 1)

result = factorial(5)
print(f"5! = {result}")
'''

script_path = os.path.join(artifacts_dir, 'test_script.py')
with open(script_path, 'w') as f:
    f.write(script_content)

print(f"脚本已创建: {script_path}")
"""
    await sandbox.execute(script_code)

    # 执行脚本
    result6 = await sandbox.execute_command("python \$SANDBOX_ARTIFACTS_DIR/test_script.py arg1 arg2")
    print(f"脚本执行成功: {result6.success}")
    print(f"输出:\n{result6.stdout}")

    print("\n" + "=" * 60)
    print("示例3完成!")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
